export const Users = [
  {
    id:1,
    profilePicture: "assets/Profile_Pictures/1.jpg",
    username: "Chang Kai Shaek",
  },
  {
    id:2,
    profilePicture: "assets/Profile_Pictures/2.jpg",
    username: "Steflana Lang",
  },
  {
    id:3,
    profilePicture: "assets/Profile_Pictures/3.jpg",
    username: "Kim-Il-Yomeni",
  },
  {
    id:4,
    profilePicture: "assets/Profile_Pictures/4.jpg",
    username: "Pablo Pascal",
  },
  {
    id:5,
    profilePicture: "assets/Profile_Pictures/5.jpg",
    username: "Vijay Yadav",
  },
  {
    id:6,
    profilePicture: "assets/Profile_Pictures/6.jpg",
    username: "Kunal Mistry",
  },
  {
    id:7,
    profilePicture: "assets/Profile_Pictures/7.jpg",
    username: "John Marcusa",
  },
  {
    id:8,
    profilePicture: "assets/Profile_Pictures/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/Profile_Pictures/9.jpg",
    username: "Rosy Sharma",
  },
  {
    id:10,
    profilePicture: "assets/Profile_Pictures/10.jpg",
    username: "Nitin",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Stonehenge Travels",
    photo: "assets/Posts/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/Posts/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/Posts/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/Posts/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/Posts/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/Posts/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/Posts/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Words of Wisdom.",
    photo: "assets/Posts/8.png",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "My new cat",
    photo: "assets/Posts/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 51,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/Posts/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
